# shellcheck disable=SC2206
# shellcheck disable=SC1090
# shellcheck disable=SC2296
# shellcheck disable=SC2164
# shellcheck disable=SC2034

# Generated by Powerlevel10k configuration wizard
'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'        ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob

  # --- Kanagawa Color Palette ---
  local sumiInk1='#1F1F28'
  local sumiInk2='#242430'
  local sumiInk3='#2A2A37'
  local fujiWhite='#DCD7BA'
  local fujiGray='#727169'
  local carpYellow='#938056'
  local springViolet='#938AA9'
  local oniViolet='#957FB8'
  local crystalBlue='#7E9CD8'
  local springGreen='#98BB6C'
  local autumnRed='#C34043'
  local autumnYellow='#DCA561'

  # --- General Prompt Settings ---
  typeset -g POWERLEVEL9K_MODE=nerdfont-complete
  typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
  typeset -g POWERLEVEL9K_LEFT_PROMPT_SEPARATOR='\uE0B0'
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_SEPARATOR='\uE0B2'
  typeset -g POWERLEVEL9K_VISUAL_IDENTIFIER_EXPANSION='${P9K_VISUAL_IDENTIFIER// }'

  # --- Left Prompt Segments (What you actually see) ---
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    context
    dir
    vcs
    vi_mode
  )

  # --- Right Prompt Segments (What you actually see) ---
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    status
    command_execution_time
    virtualenv
    go_version
    rust_version
    node_version
    time
  )

  # --- Segment Styling ---

  # Context (user@hostname)
  typeset -g POWERLEVEL9K_CONTEXT_BACKGROUND=$sumiInk3
  typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND=$fujiWhite

  # Directory
  typeset -g POWERLEVEL9K_DIR_BACKGROUND=$sumiInk2
  typeset -g POWERLEVEL9K_DIR_FOREGROUND=$crystalBlue
  typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=$springViolet
  typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=$fujiGray
  typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true

  # VCS (Git)
  typeset -g POWERLEVEL9K_VCS_BACKGROUND=$sumiInk3
  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=$springGreen
  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=$autumnYellow
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=$autumnRed
  typeset -g POWERLEVEL9K_VCS_BRANCH_ICON='\uF126'

  # Vi Mode (Normal/Insert)
  typeset -g POWERLEVEL9K_VI_MODE_NORMAL_BACKGROUND=$crystalBlue
  typeset -g POWERLEVEL9K_VI_MODE_NORMAL_FOREGROUND=$sumiInk1
  typeset -g POWERLEVEL9K_VI_MODE_INSERT_BACKGROUND=$springGreen
  typeset -g POWERLEVEL9K_VI_MODE_INSERT_FOREGROUND=$sumiInk1

  # Status (exit code)
  typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=$springGreen
  typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=$autumnRed

  # Command Execution Time
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=$fujiGray

  # Language Versions
  typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=$springGreen
  typeset -g POWERLEVEL9K_GO_VERSION_FOREGROUND=$crystalBlue
  typeset -g POWERLEVEL9K_RUST_VERSION_FOREGROUND=$autumnYellow
  typeset -g POWERLEVEL9K_NODE_VERSION_FOREGROUND=$springGreen

  # Time
  typeset -g POWERLEVEL9K_TIME_FOREGROUND=$fujiGray
  typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M}'

  # Prompt Character
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_FOREGROUND=$oniViolet
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_FOREGROUND=$autumnRed
  typeset -g POWERLEVEL9K_PROMPT_CHAR_SYMBOL='❯'
}

(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'
